### ISSUE TITLE
Getting 0 downloads when I use the script

### ISSUE THREAD

**Issue by VanishingBlaze** [itskenny0/dumpia#4]
Had a heck of a time figuring out how to get it to work. Now i'm stuck and getting 0 downloads. Was wondering if you could help me please

**Comment by itskenny0** [comment]
Please try running it with the --verbose flag and post the output as a comment.

**Comment by VanishingBlaze** [comment]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Jett>C:\php\php.exe C:\php\dumpia.php --fanclub 2931 --key 86ab236d83843d2aacbc5dcd0e85bc31 --output C:\Users\Jett\Desktop\storingfolder --verbose
[Sat, 16 Mar 2019 18:44:10 +0000][9864] dumpia - v1.0 - https://github.com/itskenny0/dumpia
[Sat, 16 Mar 2019 18:44:10 +0000][9864] Attempting to fetch page 1...
[Sat, 16 Mar 2019 18:44:10 +0000][9864] cURL: https://fantia.jp/fanclubs/2931/posts?page=1
[Sat, 16 Mar 2019 18:44:10 +0000][9864] No matches on page 1. Last fetchable page reached.
[Sat, 16 Mar 2019 18:44:10 +0000][9864] Trying 0 posts ...
[Sat, 16 Mar 2019 18:44:10 +0000][9864] Download finished.

**Comment by itskenny0** [comment]
To be honest I've never used this script in Windows. Could you tell me the PHP version you are using so I can test?

**Comment by itskenny0** [comment]
Okay, managed to reproduce it. Probably some Windows <> Linux compatibility crap. Gonna see if I can throw up some fixes.

**Comment by itskenny0** [comment]
Okay, flipping the CURL_DEBUG switch in the header reveals the issue:
```kenny@pbng MINGW64 /c/xampp/php/dumpia (master)
$ ../php.exe dumpia.php --output down --verbose --fanclub 2931--key e1170a0554304cfb44e6c8fd808078b5
[Sat, 16 Mar 2019 23:53:26 +0100][16412] dumpia - v1.0 - https://github.com/itskenny0/dumpia
[Sat, 16 Mar 2019 23:53:26 +0100][16412] Attempting to fetch page 1...
[Sat, 16 Mar 2019 23:53:26 +0100][16412] cURL: https://fantia.jp/fanclubs/1888/posts?page=1
*   Trying 130.211.10.110...
* TCP_NODELAY set
* Connected to fantia.jp (130.211.10.110) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: C:\xampp\apache\bin\curl-ca-bundle.crt
  CApath: none
[Sat, 16 Mar 2019 23:53:26 +0100][16412] No matches on page 1. Last fetchable page reached.
[Sat, 16 Mar 2019 23:53:26 +0100][16412] Trying 0 posts ...
[Sat, 16 Mar 2019 23:53:26 +0100][16412] Download finished.```

**Comment by itskenny0** [comment]
Enabling the CURL_DEBUG flag shows the issue - the Windows PHP distributions distribute cURL without a certificate trust chain, so cURL cannot establish a valid HTTPS connection to fantia.jp. The workaround I've implemented is that cURL will not check if the certificate is valid if on a Windows platform.

This would be a bad idea if this was anything security-related, but since this thing just downloads pictures I think we'll be fine.

To get the new changes, please run a git pull. It should work exactly the way you used it now.
