### ISSUE TITLE
Issue dowloading mp4 attachement

### ISSUE THREAD

**Issue by autochesser** [itskenny0/dumpia#5]
Seems that the downloader will not recognize any creators that upload .zips or mp4 files individually along with images. It will only download the images in the post and not the additional files

**Comment by itskenny0** [comment]
I don't have any galleries that post this kind of file, however the change required should be pretty simple.
I've added the requested file extensions, could you try again please?

https://github.com/itskenny0/dumpia/commit/d70281cdb87a5ed22476fe2ee068a6d66677bead
