### ISSUE TITLE
About file name decoding.

### ISSUE THREAD

**Issue by pointerphile** [itskenny0/dumpia#7]
It will be better to decode file's name in your curlToDisk() function.

`private function curlToDisk($url, $target) {`
`		$fp = fopen($target, 'w');`

like this...

`private function curlToDisk($url, $target) {`
`		$strDecodedTarget = urldecode($target);`
`		$fp = fopen($strDecodedTarget, 'w');`

then, it will save file name

>6564fa20_20190626_%E7%AE%B1%E5%B4%8E%E6%98%9F%E6%A2%A8%E8%8A%B1.png

to

>6564fa20_20190626_箱崎星梨花.png

**Comment by itskenny0** [comment]
Thank you, I've added it just as you suggested!
