### ISSUE TITLE
[enhancement] Download posts from all supporting users

### ISSUE THREAD

**Issue by noriokun4649** [itskenny0/dumpia#8]
Can you add an option to download the posts of all the users I support?

I would like to download posts from all the users I support at the end of the month.

**Comment by itskenny0** [comment]
I have added the requested feature. It can be used by just omitting the fanclub parameter, dumpia should then automatically get the list of followed fanclubs and download them accordingly. Could you please verify whether this is good for your use case now?

Thanks for the enhancement suggestion.
Best,
kenny

**Comment by noriokun4649** [comment]
Thank you from Japan!
It worked as I expected! That's right for my use case.

Thank you again.

**Comment by itskenny0** [comment]
Thanks a lot for using and reaching out for the enhancement as well as confirming it is working! I have made some further optimizations and fixed a bug, and am going to create a release for the new version now.

Best greetings from Germany, please stay healthy.
Kenny
